package com.srgnis.libredicweb;

import java.util.Map;

import static java.util.Map.entry;


public final class Verboser {

    public static Map<String, String> valor = Map.ofEntries(
        entry("ATO","ordinal"),
        entry("ATQ","qualificativo"),
        entry("ATP","posesivo"),
        entry("ADS","superlativo"),
        entry("ADV","evaluativo"),
        entry("AGF","femenino"),
        entry("AGM","masculino"),
        entry("AGC","comun"),
        entry("ANS","singular"),
        entry("ANP","plural"),
        entry("ANN","invariable"),
        entry("APP1","1"),
        entry("APP2","2"),
        entry("APP3","3"),
        entry("APNS","singular"),
        entry("APNP","plural"),
        entry("APNN","invariable"),
        entry("CTC","coordinantes"),
        entry("CTS","subordinantes"),
        entry("DTA","articulo"),
        entry("DTD","demostrativo"),
        entry("DTI","indefindo"),
        entry("DTP","posesivo"),
        entry("DTT","interrogativo"),
        entry("DTE","exclamativo"),
        entry("DPN1","1"),
        entry("DPN2","2"),
        entry("DPN3","3"),
        entry("DGF","femenino"),
        entry("DGM","masculino"),
        entry("DGC","comun"),
        entry("DNS","singular"),
        entry("DNF","plural"),
        entry("DNC","comun"),
        entry("DPNS","singular"),
        entry("DPNF","plural"),
        entry("DPNC","comun"),
        entry("NTC","comun"),
        entry("NTP","propio"),
        entry("NGF","femenino"),
        entry("NGM","masculino"),
        entry("NGC","comun"),
        entry("NNS","singular"),
        entry("NNP","plural"),
        entry("NNN","invariable"),
        entry("NNCS","persona"),
        entry("NNCG","lugar"),
        entry("NNCO","organizacion"),
        entry("NNCV","otro"),
        entry("NDV","evaluativo"),
        entry("PTD","demostrativo"),
        entry("PTE","exclamativo"),
        entry("PTI","indefinido"),
        entry("PTP","personal"),
        entry("PTR","relativo"),
        entry("PTT","interrogativo"),
        entry("PPN1","1"),
        entry("PPN2","2"),
        entry("PPN3","3"),
        entry("PGF","femenino"),
        entry("PGM","masculino"),
        entry("PGC","comun"),
        entry("PNS","singular"),
        entry("PNP","plural"),
        entry("PNN","invariable"),
        entry("PCN","nominativo"),
        entry("PCA","acusativo"),
        entry("PCD","dativo"),
        entry("PCO","oblicuo"),
        entry("PPP","formal"),
        entry("RTN","negativo"),
        entry("RTG","general"),
        entry("STP","preposicion"),
        entry("VTM","principal"),
        entry("VTA","auxiliar"),
        entry("VTS","semiauxiliar"),
        entry("VMI","indicativo"),
        entry("VMS","subjuntivo"),
        entry("VMM","imperativo"),
        entry("VMP","participio"),
        entry("VMG","gerundio"),
        entry("VMN","infinitivo"),
        entry("VTNP","presente"),
        entry("VTNI","imperfecto"),
        entry("VTNF","futuro"),
        entry("VTNS","pasado"),
        entry("VTNC","condicional"),
        entry("VPN1","1"),
        entry("VPN2","2"),
        entry("VPN3","3"),
        entry("VNS","singular"),
        entry("VNP","plural"),
        entry("VGF","femenino"),
        entry("VGM","masculino"),
        entry("VGC","comun"),
        entry("ZTD","partitivo"),
        entry("ZTM","moneda"),
        entry("ZTP","porcentage"),
        entry("ZTU","unidad")
    );

    public static Map<String, String> categoria = Map.ofEntries(
            entry("A","adjetivo"),
            entry("C","conjuncion"),
            entry("D","determinante"),
            entry("N","nombre"),
            entry("P","pronombre"),
            entry("R","adverbio"),
            entry("S","aposicion"),
            entry("V","verbo"),
            entry("Z","numero"),
            entry("W","fecha"),
            entry("I","interjeccion")
    );

    public static Map<String, String> tipo = Map.ofEntries(
            entry("T","tipo"),
            entry("D","grado"),
            entry("G","genero"),
            entry("N","numero"),
            entry("PP","poseedorper"),
            entry("PN","poseedornum"),
            entry("NC","neclass"),
            entry("NSC","nesubclass"),
            entry("C","caso"),
            entry("P","formal"),
            entry("M","modo"),
            entry("TN","tiempo"),
            entry("PR","persona")
    );

}
